hypatia_repo: https://github.com/hypatia-software-organization/hypatia-engine

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    -
        scope:
            path: "wiki"
            type: "pages"
        values:
            layout: "wiki"

markdown: kramdown
kramdown:
    input: GFM
sass:
    sass_dir: _sass
    style: :compressed
